---
- name: Create postgresql superuser with encrypted password this will be the only user of the db
  shell: |
    psql -c "SELECT 1 FROM pg_roles WHERE rolname='{{ database_user }}'" | grep -q 1 ||  
    psql -c "CREATE USER {{ database_user }} WITH SUPERUSER ENCRYPTED PASSWORD '{{ database_password }}';"
  become_user: postgres

- name: Create database
  shell: | 
    psql -l | grep "{{ database_name }}" ||
    psql -c "CREATE DATABASE {{ database_name }};"
  become_user: postgres
