---
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: yes
  vars_files:
    - ./group_vars/database.yaml
    - ./group_vars/domain.yaml
    - ./group_vars/next.yaml
  roles:
    - role: postgres
    - role: nginx
    - role: certbot
    - role: td-agent
    - role: rsyslogd
    - role: docker-swarm
  tasks:

    ##################################################
    # Configure psql database
     
    - name: Create postgresql superuser with encrypted password this will be the only user of the db
      shell: |
        psql -c "SELECT 1 FROM pg_roles WHERE rolname='{{ database_user }}'" | grep -q 1 ||  
        psql -c "CREATE USER {{ database_user }} WITH SUPERUSER ENCRYPTED PASSWORD '{{ database_password }}';"
      become_user: postgres
      no_log: true

    - name: Create database
      shell: | 
        psql -l | grep "{{ database_name }}" ||
        psql -c "CREATE DATABASE {{ database_name }};"
      become_user: postgres
      no_log: true

    ##################################################
    # Install certificates
    
    - name: Obtain certificates and modify nginx config
      shell: certbot --nginx --non-interactive --agree-tos -m {{ admin_email_gmail }} --domain {{ domain_name }}

    ##################################################
    # Configure Nginx as a reverse proxy
    
    - name: Add ansible markers in /etc/nginx/sites-available/default
      shell: perl -0 -i -pe 's/(.*server {.*?location \/ {)(.*?)(}.*? listen \[::\]:443 ssl ipv6only=on;.*)/\1\n# BEGIN ANSIBLE MANAGED BLOCK\n# END ANSIBLE MANAGED BLOCK\n\3/gms' /etc/nginx/sites-available/default

    # Configure Nginx as reverse proxy added configs for Phoenix
    - name: Fill the location block of the ssl block
      blockinfile:
        path: /etc/nginx/sites-available/default
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          allow all;

          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-Cluster-Client-Ip $remote_addr;

          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          proxy_pass http://localhost:8000;

    - name: Check whether the nginx configuration is valid
      shell: nginx -t

    - name: Restart the Nginx service
      ansible.builtin.systemd:
        name: nginx.service
        state: restarted
        daemon_reload: true


    ##################################################
    # Build and Run Next with Docker
    
    - name: Clone Next from Github
      git:
        repo: https://github.com/d3i-infra/mono
        update: yes
        dest: ./mono

    - name: Build Next with Docker build
      shell:
        cmd: docker build --build-arg VERSION=1.0.0 --build-arg BUNDLE=self . -t next:latest
        chdir: mono/core

    - name: Start Next on Docker Swarm with a compose file as user 'dockeruser'
      shell: |
        cat - <<EOF | docker stack deploy --compose-file - nextdeployment
        version: "3.9"

        services:
           next:
             image: next:latest
             environment:
               APP_NAME: "{{ app_name }}"
               APP_DOMAIN: "{{ domain_name }}"
               APP_MAIL_DOMAIN: @gmail
               APP_ADMINS: "{{ admin_email_gmail }}"
               DB_NAME: "{{ database_name }}"
               DB_HOST: 172.17.0.1
               DB_USER: "{{ database_user }}"
               DB_PASS: "{{ database_password }}"
               SECRET_KEY_BASE: "{{ secret_key_base }}"
               STATIC_PATH: /var/tmp
               UNSPLASH_ACCESS_KEY: "{{ unsplash_access_key }}"
               UNSPLASH_APP_NAME: "{{ unsplash_app_name }}"
               GOOGLE_SIGN_IN_CLIENT_ID: "{{ google_sign_in_client_id }}"
               GOOGLE_SIGN_IN_CLIENT_SECRET: "{{ google_sign_in_client_secret }}"
             logging:
               driver: "fluentd"
               options:
                 fluentd-address: 172.17.0.1:24224
                 tag: next
             ports:
                 - target: 8000
                   published: 8000
                   mode: host
        EOF
      become_user: dockeruser
